### ISSUE TITLE
엔티티 객체 연관관계 설정

### ISSUE THREAD

**Issue by no-cy** [f-lab-edu/market-nori#3]
# 🧑🏻‍💻 진행할 작업
* 엔티티 연관 관계 설정

# 📝 TODO
* [x] 유저, 주문 
* [x] 유저, 장바구니 
* [x] 장바구니, 장바구니 상품 목록
* [x] 상품, 장바구니 상품 목록
* [x] 상품, 상품 카테고리
* [x] 주문, 주문 상품 목록
* [x] 주문, 결제

**Comment by no-cy** [comment]
- [x] 상품, 장바구니 상품 목록 연관 관계 설정 **(추가)**
